### ISSUE TITLE
Send "received" notification mail to author

### ISSUE THREAD

**Issue by michaelalemu** [Notanotherdotcom/ProcessEmailToPage#10]
Hi, I'm using your wonderful module within a small organisation. When people send content to the website, they are left unsure whether the website has received the mail. It would be great if a notification mail is sent to the author.

Best
Michael

**Comment by adrianbj** [comment]
@michaelalemu - it already has that functionality. Do you have the "Notify Users via Email" section configured?

**Comment by adrianbj** [comment]
Just occurred to me that maybe this doesn't really work as you want. Rather than pre-specified users, you want the author to be notified. Should be a fairly simple addition - I'll take a look in the next couple of days, unless you want to send a PR :)

**Comment by michaelalemu** [comment]
Hi, thanks for the fast reply. Yep, it'd be great if the author gets notified :)
Apropos pre-specified users, one further addition could be the option of selecting different users for each category to be notified. E.g. for category "news": user A gets notified, for category "events": user B gets notified. Currently user A and user B will be notified.

Best
Michael

**Comment by adrianbj** [comment]
Hi @michaelalemu - sorry for the delay, but you should now have both the features you requested. Please let me know if you have any problems and close this if you feel everything works as expected.

**Comment by michaelalemu** [comment]
Super cool, thank you for implementing this :D
