### ISSUE TITLE
Error When Retrieving Emails From URL CRON Script

### ISSUE THREAD

**Issue by cstevensjr** [Notanotherdotcom/ProcessEmailToPage#3]
I finally got around to using Version 1.1.5 (Beta) to test.  I received an error when using the URL string to activate checking the mailboxes for messages.

![process-to-email-error](https://cloud.githubusercontent.com/assets/7488817/5908248/b2478ca2-a55a-11e4-9b4a-e31c6f400e19.png)

Any  thoughts on how to avoid this is appreciated.  I ended up reverting to Version 1.1.4 and had no problems.  At the time I was using PW 2.5.13 Dev

**Comment by adrianbj** [comment]
Sorry about that. I am super-busy right now, but I have just committed an untested fix that should work. Sorry I don't have time to test properly. Please let me know how it works for you.

**Comment by cstevensjr** [comment]
Should have been closed in January. Sorry
