### ISSUE TITLE
Error Connecting To Server (Version 1.1.6)

### ISSUE THREAD

**Issue by cstevensjr** [Notanotherdotcom/ProcessEmailToPage#5]
I recently installed this module and I am receiving the following error:

![email-to-page](https://cloud.githubusercontent.com/assets/7488817/9250452/0027b000-419b-11e5-8ae5-30cc790e4d79.png)

ProcessWire 2.6.12 dev, PHP 5.5.x

I have a similar installation (Version 1.1.4) working great under ProcessWire 2.5.22, PHP 5.4.x

**Comment by adrianbj** [comment]
Hi @cstevensjr - i just tested with PHP 5.6.6 and PW 2.6.12 and had no problem connecting. Based on the error it does look like it's an issue with the Flourish library connecting to the email address. Have you tested with the same email address you were using successfully on the other site?

I know you are very savvy with email connections so I am guessing you have all the settings correct, but that is all I can think it could be.

**Comment by cstevensjr** [comment]
Ok, I finally figured this out.  It was a configuration problem on my webhost (Dreamhost).

My webhost uses mail clusters for outgoing mail.  I've never had a problem before where I needed to list the mail cluster name for the "Host" setting.  When I finally changed the setting to the mail cluster name, the Flourishlib portion worked without error.

Closing this issue
