### ISSUE TITLE
Adding Additional New Category Doesn't Allow You To Select The Page

### ISSUE THREAD

**Issue by cstevensjr** [Notanotherdotcom/ProcessEmailToPage#6]
Unfortunately, I ran into another issue.  When I try to add "A New Category" the display comes up, however there is no way to select the page you want the category to be.

![category-1](https://cloud.githubusercontent.com/assets/7488817/9289136/0a3adbe0-4334-11e5-9d1f-9933170033c4.png)
Figure 1, Category 1 works the way it should.

![category-2](https://cloud.githubusercontent.com/assets/7488817/9289113/425053ee-4333-11e5-87c2-f550e4c0b508.png)
Figure 2, Category 2 doesn't allow you to select a page.

This is Version 1.1.6 using PW 2.6.13 on PHP 5.6.x

**Comment by adrianbj** [comment]
Should be fixed in the latest commit. This takes care of making this module work with PW version 2.6.6+ and it should still work fine on previous versions.

Please let me know if it works OK for you.

**Comment by cstevensjr** [comment]
Working great! Closing this issue
